# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_fullName', models.CharField(max_length=1000)),
                ('emp_shortForm', models.CharField(max_length=500)),
                ('emp_code', models.CharField(max_length=500)),
                ('emp_type', models.CharField(max_length=255)),
                ('emp_designation', models.CharField(max_length=255)),
                ('emp_priority', models.IntegerField(default=0)),
            ],
        ),
    ]
