# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabusApp', '0005_auto_20171124_1701'),
        ('employeeApp', '0002_auto_20171120_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAssignTeacher',
            fields=[
                ('courseAssignTeacher_Id', models.AutoField(primary_key=True, serialize=False)),
                ('courseAssignTeacher_course_Id_Fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabusApp.Course')),
                ('courseAssignTeacher_syllabus_Id_Fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabusApp.Syllabus')),
                ('emp_Id_Fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeApp.Employee')),
            ],
        ),
    ]
