# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0003_courseassignteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_type',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Staff', 'Staff')], max_length=255),
        ),
    ]
