# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0005_auto_20171203_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityHandling',
            fields=[
                ('priorityHandling_Id', models.AutoField(primary_key=True, serialize=False)),
                ('priority_start', models.CharField(max_length=500)),
                ('priority_end', models.CharField(max_length=500)),
                ('priority_status', models.CharField(max_length=500)),
                ('emp_teacher_Id_Fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeApp.Employee')),
            ],
        ),
    ]
