# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-16 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0007_employee_emp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
