# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0003_courseenrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='courseEnrollment_exam_Id_Fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examApp.Exam'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='courseEnrollment_syllabus_Id_Fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabusApp.Syllabus'),
        ),
    ]
