# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0004_auto_20171122_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseenrollment',
            name='courseEnrollment_exam_Id_Fk',
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='courseEnrollment_syllabus_Id_Fk',
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='std_Id_Fk',
        ),
        migrations.DeleteModel(
            name='CourseEnrollment',
        ),
    ]
