# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examApp', '0001_initial'),
        ('syllabusApp', '0001_initial'),
        ('studentApp', '0005_auto_20171122_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('courseEnrollment_Id', models.AutoField(primary_key=True, serialize=False)),
                ('courseEnrollment_exam_Id_Fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examApp.Exam')),
                ('courseEnrollment_syllabus_Id_Fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabusApp.Syllabus')),
                ('std_Id_Fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentApp.Student')),
            ],
        ),
    ]
