# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabusApp', '0001_initial'),
        ('studentApp', '0007_auto_20171122_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='courseEnrollment_syllabus_Id_Fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='syllabusApp.Syllabus'),
            preserve_default=False,
        ),
    ]
