# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('syllabusApp', '0002_delete_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('syllabus_Id', models.AutoField(primary_key=True, serialize=False)),
                ('syllabus_level', models.CharField(max_length=500)),
                ('syllabus_duration', models.CharField(max_length=1000)),
            ],
        ),
    ]
