# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabusApp', '0003_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=500)),
                ('course_name', models.CharField(max_length=500)),
                ('course_credit', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl_name', models.CharField(choices=[('Bachelor of Science (B.Sc.)', 'Bachelor of Science (B.Sc.)'), ('Master of Science (M.Sc.)', 'Master of Science (M.Sc.)')], max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=500)),
                ('level_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabusApp.Level')),
            ],
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='syllabus_Id',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='syllabus_duration',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='syllabus_level',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='syl_session',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='level_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabusApp.Level'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabusApp.Semester'),
        ),
        migrations.AddField(
            model_name='course',
            name='syl_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabusApp.Syllabus'),
        ),
    ]
