# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('othersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='holiday_date',
            field=models.DateField(default=10.0, max_length=255),
            preserve_default=False,
        ),
    ]
