# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('othersApp', '0004_delete_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('holiday_Id', models.AutoField(primary_key=True, serialize=False)),
                ('holiday_date', models.CharField(max_length=255)),
                ('holiday_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
