# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('othersApp', '0006_auto_20171120_0343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassRoom',
        ),
        migrations.DeleteModel(
            name='ClassTime',
        ),
        migrations.DeleteModel(
            name='Holiday',
        ),
    ]
