# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('othersApp', '0007_auto_20171120_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('room_Id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('Normal', 'Normal'), ('Computer lab', 'Computer lab'), ('Electronics lab', 'Electronics lab')], max_length=500)),
                ('room_number', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('time_Id', models.AutoField(primary_key=True, serialize=False)),
                ('time_period', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('holiday_Id', models.AutoField(primary_key=True, serialize=False)),
                ('holiday_date', models.CharField(max_length=500)),
                ('holiday_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
