# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('othersApp', '0009_delete_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('holiday_Id', models.AutoField(primary_key=True, serialize=False)),
                ('holidayStart_date', models.CharField(max_length=500)),
                ('holidayEnd_date', models.CharField(max_length=500)),
                ('holiday_description', models.CharField(max_length=1000)),
                ('holidayInDays', models.CharField(max_length=500)),
            ],
        ),
    ]
