# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('othersApp', '0011_auto_20171128_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='holidayEnd_date',
            field=models.DateField(max_length=500),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='holidayStart_date',
            field=models.DateField(blank=True, max_length=500),
        ),
    ]
