# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndClass',
            fields=[
                ('endclass_Id', models.AutoField(primary_key=True, serialize=False)),
                ('startingDate', models.CharField(max_length=1000)),
                ('endingDate', models.CharField(max_length=1000)),
                ('classHeldWeek', models.CharField(max_length=500)),
                ('exam_Id_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examApp.Exam')),
            ],
        ),
    ]
