# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classRoutineApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endclass',
            name='classHeldWeek',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='endclass',
            name='startingDate',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
