# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classRoutineApp', '0002_auto_20171128_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endclass',
            name='classHeldWeek',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='endclass',
            name='startingDate',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
