# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classRoutineApp', '0003_auto_20171203_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endclass',
            name='classHeldWeek',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='endclass',
            name='endingDate',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='endclass',
            name='startingDate',
            field=models.CharField(max_length=1000),
        ),
    ]
