# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classRoutineApp', '0005_auto_20171204_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endclass',
            name='exam_Id_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examApp.Exam'),
        ),
    ]
