# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('othersApp', '0013_auto_20171128_1945'),
        ('employeeApp', '0005_auto_20171203_2314'),
        ('syllabusApp', '0005_auto_20171124_1701'),
        ('classRoutineApp', '0006_auto_20171204_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoutine',
            fields=[
                ('classRoutine_Id', models.AutoField(primary_key=True, serialize=False)),
                ('dayOfWeek', models.CharField(choices=[('Sat', 'Sat'), ('Sun', 'Sun'), ('Mon', 'Mon'), ('Tues', 'Tues'), ('Wed', 'Wed'), ('Thurs', 'Thurs'), ('Fri', 'Fri')], max_length=500)),
                ('assignedTeacher_Fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeApp.CourseAssignTeacher')),
                ('classRoom_Id_Fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='othersApp.ClassRoom')),
                ('classTime_Id_Fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='othersApp.ClassTime')),
                ('course_Id_Fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabusApp.Course')),
            ],
        ),
    ]
