# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-12 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classRoutineApp', '0007_classroutine'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroutine',
            name='semesterTry',
            field=models.CharField(default='1st', max_length=500),
        ),
    ]
