# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-13 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classRoutineApp', '0009_auto_20180213_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroutine',
            name='teacher_Id_Fk',
            field=models.IntegerField(default=0),
        ),
    ]
