# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-13 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classRoutineApp', '0010_classroutine_teacher_id_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroutine',
            old_name='teacher_Id_Fk',
            new_name='teacher_Id',
        ),
    ]
